language: java
# Run build on a Trusty image. Precise images do not support OpenJDK 8
# dist: trusty
# sudo: false

jdk:
    # - openjdk8
    - oraclejdk8

after_success:
  - ./gradlew cobertura pitest coveralls

script:
    - ./gradlew build

cache:
  directories:
      - "$HOME/.gradle/caches"
      - "$HOME/.m2"
      - "$HOME/.gradle/wrapper/dists"

notifications:
  email: false
